### ISSUE TITLE
BASE HTTP SERVER exception

### ISSUE THREAD

**Issue by djphil** [Misterblue/SimStats#1]
Sometimes i get this red alert on my simulator console :

20:26:58 - [BASE HTTP SERVER]: HandleRequest() threw exception System.InvalidOpe
rationException: La collection a été modifiée après l'instanciation de l'énuméra
teur.
   à System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resourc
e)
   à System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   à System.Collections.Generic.SortedDictionary`2.Enumerator.MoveNext()
   à System.Collections.Generic.SortedDictionary`2.KeyCollection.Enumerator.Move
Next()
   à OpenSim.Framework.Monitoring.StatsManager.GetStatsAsOSDMap(String pCategory
Name, String pContainerName, String pStatName) dans k:\OSGRID\opensim-43c8e23\Op
enSim\Framework\Monitoring\StatsManager.cs:ligne 265
   à OpenSim.Framework.Monitoring.StatsManager.HandleStatsRequest(Hashtable requ
est) dans k:\OSGRID\opensim-43c8e23\OpenSim\Framework\Monitoring\StatsManager.cs
:ligne 312
   à OpenSim.Framework.Servers.HttpServer.BaseHttpServer.HandleContentVerbs(OSHt
tpRequest request, OSHttpResponse response) dans k:\OSGRID\opensim-43c8e23\OpenS
im\Framework\Servers\HttpServer\BaseHttpServer.cs:ligne 1653
   à OpenSim.Framework.Servers.HttpServer.BaseHttpServer.HandleHTTPRequest(OSHtt
pRequest request, OSHttpResponse response) dans k:\OSGRID\opensim-43c8e23\OpenSi
m\Framework\Servers\HttpServer\BaseHttpServer.cs:ligne 1555
   à OpenSim.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(OSHttpReq
uest request, OSHttpResponse response) dans k:\OSGRID\opensim-43c8e23\OpenSim\Fr
amework\Servers\HttpServer\BaseHttpServer.cs:ligne 632

**Comment by Misterblue** [comment]
This is a problem with OpenSimulator not locking its data structures. The fix is a patch to OpenSimulator.
